# Generated by Django 5.1.6 on 2025-03-03 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='user',
            new_name='applicant',
        ),
    ]
